<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

### Exercise 1

| Term       | Brief Description                                              |
|------------|----------------------------------------------------------------|
| Subsetting | _Selecting part(s) of the original list/ array_                 |
| Indexing   | _Selecting one element from the list/ array_                  |
| Slicing    | _Selecting a range of elements from the list/array_           |
| Masking    | Returns a filtered list with elements that result in   "True"  |

### Exercise 2 

In [32]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

arr_1 = np_array_2d[:,0]
arr_2 = arr_1.astype('i')
arr_3 = arr_2 % 2
mask = arr_3 == 1
np_array_2d[mask,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

### Exercise 3

In [33]:
import numpy as np
arr = np.array([[66, 50, 57, -1, -1],
        [92, -1, 88, -1, -1],
        [75, -1, -1, 76, -1],
        [-1, 51, 87, -1, -1],
        [71, -1, 67, -1, 69]])

arr[arr < 50] =-1
arr[arr > 50] = 1
arr[arr == 50] = 0
print(arr)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
