<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [1]:
import numpy as np

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [ ]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [2]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

## 1.2 Accessing data from a list (or array)

In [15]:

py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
print(py_super_names[0])
print(py_real_names[0])

i = -3
print(py_super_names[i],"is", py_real_names[i])

Black Widow
Natasha Romanoff
Black Widow is Natasha Romanoff


In [11]:
py_super_names[-1]

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [19]:
superhero_info = {
    "Natasha Romanoff":"Black Widow", 
    "Tony Stark":"Iron Man", 
    "Stephen Strange":"Doctor Strange"
}

#Adding
superhero_info["Peter Parker"] = "Spiderman"
print(superhero_info)

{'Natasha Romanoff': 'Black Widow', 'Tony Stark': 'Iron Man', 'Stephen Strange': 'Doctor Strange', 'Peter Parker': 'Spiderman'}


## 1.4 Higher dimensional lists

In [ ]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [22]:
py_superhero_info = [
    ['Natasha Romanoff', 'Black Widow'],
    ['Tony Stark', 'Iron Man'], 
    ['Stephen Strange', 'Doctor Strange']
]

py_superhero_info[-1][0]

'Stephen Strange'

# 2 Lists vs. Arrays

In [ ]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)  #Casting -> recast data into another form



numpy.ndarray

In [26]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [28]:
np_array_2d  #np arrays only like one type of data

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

## 2.1 Size

In [ ]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [29]:
len(py_list_2d)

10

In [30]:
len(np_array_2d)

10

In [31]:
np_array_2d.size

20

In [32]:
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

In [ ]:
#Fussy anout having homogenous shape
np_array_2d.shape = np.array([[1, "A" , 3], [2, "B", 4], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]])  #Numpy need to have same number of elements while lists dont need (need homogeneous shape throughout)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10,) + inhomogeneous part.

## 2.3 Adding a number

In [37]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [ ]:
py_list + 100

TypeError: can only concatenate list (not "int") to list

In [41]:
np_array + 22

array([23, 24, 25, 26, 27])

## 2.4 Adding another list

In [44]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)
print(np_array_1, np_array_2, sep = '\n')

[1 2 3 4 5]
[10 20 30 40 50]


In [45]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

In [46]:
py_list + [100]

[1, 2, 3, 4, 5, 100]

In [47]:
py_list + [100, 200]

[1, 2, 3, 4, 5, 100, 200]

In [48]:
np_array_1 + [100]

array([101, 102, 103, 104, 105])

In [49]:
np_array_1 + [100, 200]

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

## 2.5 Multiplying by a Number

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [51]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [50]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

## 2.7 Asking questions

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [54]:
print(py_list == 3)     # Works, but what IS the question?
print(np_array == 3)  
print(np_array > 3)

False
[False False  True False False]
[False False False  True  True]


In [53]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [57]:
sum(np_array > 3)

np.int64(2)

In [ ]:
#Masking
a = np_array >3
np_array[a]

array([4, 5])

In [62]:
np_array[mask].sum()

np.int64(9)

In [75]:
py_list = [1,2,3,4,5]*10
np_array = np.array(py_list)
mask = np_array <3
np_array[mask]

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

## 2.8 Mathematics

In [79]:
py_list = [1,2,3,4,5]*10
np_array = np.array(py_list)
mask = np_array <3
np_array[mask]

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

In [80]:
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()

np.float64(1.4142135623730951)

In [81]:
mean = sum(py_list) / len(py_list)
print(mean)

3.0


AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [89]:
np_array.mean()

np.float64(3.0)

In [88]:
np.mean(np_array)

np.float64(3.0)

In [91]:
np_array.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
np.median(np_array)

np.float64(3.0)

In [ ]:
np.median(help)

TypeError: unsupported operand type(s) for /: '_Helper' and 'int'

## Footnotes