<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [1]:
import numpy as np

### Accessing Data from Lists and Arrays

- Items in lists and arrays are ordered, so each item will have an index (position). The first element will have an index of 0

- Negative indexing (Backwards) can also be used. The last element will have an index of -1

- Syntax for accessing items: `variable[index]`

In [ ]:
example_list = ['A', 'B', 'C', 'D', 'E']
print(example_list[0])  #A
print(example_list[4])  #E

#Same for arrays
example_arr = np.array(example_list)
print(example_arr[0])  #A
print(example_arr[4])  #E

A
E
A
E


---

### Accessing Data from Dictionary 

- Dictionaries store items in a key:value format 

- A value can be accessed by calling its respective key

In [ ]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

print(superhero_info["Natasha Romanoff"])  #Black Widow
print(superhero_info["Black Widow"])  #Calling the value will return a KeyError 

Black Widow


In [ ]:
#Accessing all keys
print(superhero_info.keys())  #dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

#Accessing all values
print(superhero_info.values())  #dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

#Accessing all items
print(superhero_info.items())  #dict_items([('Natasha Romanoff', 'Black Widow'), ('Tony Stark', 'Iron Man'), ('Stephen Strange', 'Doctor Strange')])

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])
dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])
dict_items([('Natasha Romanoff', 'Black Widow'), ('Tony Stark', 'Iron Man'), ('Stephen Strange', 'Doctor Strange')])


In [55]:
#Adding items

#Items can be added using dict_name[key] = value
superhero_info = {
    "Natasha Romanoff":"Black Widow", 
    "Tony Stark":"Iron Man", 
    "Stephen Strange":"Doctor Strange"
}

superhero_info["Peter Parker"] = "Spiderman"
print(superhero_info)

{'Natasha Romanoff': 'Black Widow', 'Tony Stark': 'Iron Man', 'Stephen Strange': 'Doctor Strange', 'Peter Parker': 'Spiderman'}


---

# Lists vs. Arrays

### Size

- len() can be called on both lists and arrays to return the number of items (Can only count for outermost dimension)

- shape attribute (`arr_name.shape`) can only be used on arrays to return the number of items in each dimension 


In [11]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)  #Casting -> recast data into another form

#len() function -> Notice it can only count the number of items in the 1st dimension, not the 0th dimension 
print(len(py_list_2d))
print(len(np_array_2d))

#shape attribute -> can count number of elements in 1st dimension and 0th dimension 
print(np_array_2d.shape)


10
10
(10, 2)


- Arrays need to have the same shape while lists do not

In [53]:
list2d = [[1,2,3], [4,5]]
print(list2d)

print(np.array(list2d))

[[1, 2, 3], [4, 5]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

---

### Data Type Consistency 

- Lists can accomodate different data types. However, arrays need to have the same data type 

In [14]:
py_list = [1, 1.5, 'A']
np_arr = np.array(py_list)
print(py_list)
print(np_arr)  #Python converts all the items to strings 

[1, 1.5, 'A']
['1' '1.5' 'A']


---

### Adding a Number

- Numbers can be added to arrays but not to lists 

In [ ]:
py_list = [1,2,3,4,5]
np_arr= np.array(py_list)

print(np_arr + 10)  #[11 12 13 14 15]
print(py_list + 10) #Type Error. Cannot concatenate list to integer 

[11 12 13 14 15]


TypeError: can only concatenate list (not "int") to list

---

### Adding lists/ arrays to each other

- Adding lists causes them to grow

- Adding arrays is an element-wise operation

In [17]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

print(py_list_1 + py_list_2)  #[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
print(np_array_1 + np_array_2)  #[11 22 33 44 55]

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[11 22 33 44 55]


---

### Multiplying lists/ arrays to a number

- Multiplying a list to a number causes the list to grow

- Multiply an array to a number multiplies the elements by the number

In [ ]:
py_list = [1, 2, 3, 4, 5] 
np_arr = np.array(py_list)

print(py_list * 2)  #[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
print(np_arr * 2)  #[ 2  4  6  8 10]

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


---

### Squaring

- Lists cannot be squared

- Squaring an array squares the individual elements 

In [ ]:
py_list = [1, 2, 3, 4, 5] 
np_arr = np.array(py_list)

print(np_arr ** 2)  #[ 1  4  9 16 25]
print(py_list ** 2)  #TypeError 

[ 1  4  9 16 25]


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

---

### Asking Questions

- Comparison operators works on arrays but not lists

- Using comparison operators on arrays will return an array of Boolean values 

In [ ]:
py_list = [1, 2, 3, 4, 5] 
print(py_list == 3)  #Nonsense Output
print(py_list > 3)  #TypeError

np_arr = np.array(py_list)
print(np_arr == 3)  #[False False  True False False]
print(np_arr > 3)  #[False False False  True  True]


False
[False False  True False False]
[False False False  True  True]


---

### Mathematical Functions 

In [30]:
py_list = [1, 2, 3, 4, 5] 
print(sum(py_list))
print(max(py_list))
print(min(py_list))

np_arr = np.array(py_list)
print(np_arr.sum())
print(np_arr.max())
print(np_arr.min())
print(np_arr.mean())
print(np_arr.std())

15
5
1
15
5
1
3.0
1.4142135623730951


---

In [26]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [28]:
np_array_2d  #np arrays only like one type of data

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')