<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

In [ ]:
print("Testing")

# 1 Subsetting: Indexing and Slicing

In [22]:
import numpy as np
py_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
np_array = np.array(py_list)


In [20]:
py_list[2:5]

[3, 4, 5]

In [29]:
print(py_list[0:5:-1])

[]


In [17]:
np_array_2d = np.split([[1,2,3,4,5,6,7,8,9]], [1,2])
print(np_array_2d)

[array([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), array([], shape=(0, 9), dtype=int64), array([], shape=(0, 9), dtype=int64)]


In [ ]:
# mask will always be same size as input  
# once you subset using a mask, the output has smaller size than the input

In [30]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [31]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [32]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [34]:
np_array[(np_array >3) & (np_array < 7)]  #Masking

array([4, 5, 6])

In [35]:
np_array[(np_array >3) | (np_array < 7)]  #Masking

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

## 1.2 Arrays only | Subsetting by masking

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [ ]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [45]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [46]:
py_list_2d[3]

[4, 'D']

In [47]:
py_list_2d[3][1]

'D'

In [48]:
np_array_2d[3,0]

np.str_('4')

In [50]:
np_array_2d[:,0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [51]:
np_array_2d[3:,0]

array(['4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [63]:
py_list_2d[3:][:][0]

[4, 'D']

## 1.4 Growing lists

In [ ]:
x = [1,2] + [3]
x = x + [4]
x = x + [5]
print(x)

[1, 2, 3, 4, 5]


In [ ]:
x = [1,2]
x.append([3,4,5])
print(x)
# can only append one element at a time



[1, 2, [3, 4, 5]]


# Some loose ends

## 1.5 Tuples

In [75]:
a = (1,2,3)
b = [1,2,3]

In [76]:
a + [1]

TypeError: can only concatenate tuple (not "list") to tuple

In [77]:
b + [1]

[1, 2, 3, 1]

## 1.6 Be VERY careful when copying

In [82]:
x = [1,2,3]
y = x
z = x
print(x,y,z)

[1, 2, 3] [1, 2, 3] [1, 2, 3]


In [83]:
x.append(1)
print(x,y,z)

[1, 2, 3, 1] [1, 2, 3, 1] [1, 2, 3, 1]


In [84]:
z.append(1000)
print(x,y,z)

[1, 2, 3, 1, 1000] [1, 2, 3, 1, 1000] [1, 2, 3, 1, 1000]


In [85]:
# do not copy like this

In [86]:
c = [1,2,3]
b = c.copy()
c.append(5)
print(b,c)

[1, 2, 3] [1, 2, 3, 5]


## Footnotes